# -*- coding: utf-8 -*-
"""Handwirtten Digit recog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UFyJTm7XLpKdUqo2sqiwJtIp_MxTjtQP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

train_data = pd.read_csv('/content/Train (1).csv')
print("Shape of train_data:", train_data.shape)

X = train_data.iloc[:, 1:]
y = train_data.iloc[:, 0]

print("Shape of X after separating features:", X.shape)

# ensure X is inthe correct format(Pandas DataFrame)
if not isinstance(X, pd.DataFrame):
    X = pd.DataFrame(X)
# Convert all pixel values to numeric format and replace any missing values with 0
X = X.apply(pd.to_numeric, errors='coerce').fillna(0)

# Normalize the pixel values to the range [0, 1] by dividing them by 255.0. This helps the model learm faster.
X = X.values / 255.0

# Finally we reshape the data to include a channel dimension making it compatible with neural networks
X = X.reshape(-1, 28, 28, 1)
print("Shape of X after reshaping:", X.shape)

# One-Hot Encode the Labels
y = train_data.iloc[:, 0] # Re-extract original labels to ensure correct shape
y = to_categorical(y, num_classes=10)
print("Shape of y after one-hot encoding:", y.shape)

# Split the data into train-test
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)

"""A Flatten layer converts the 28x28 image into a single vector of length 784.

Two hidden layers with 128 and 64 neurons use the ReLU activation function to introduce non-linearity.

An output layer with 10 neurons uses the softmax activation function to predict probabilities for each digit (0-9).

We compile the model with the Adam optimizer, categorical cross-entropy loss, and accuracy as the evaluation metric.
"""

model = Sequential()
model.add(Flatten(input_shape=(28, 28, 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(X_train,
                    y_train,
                    epochs=10,
                    batch_size=32,
                    validation_data=(X_val, y_val)
                    )

history.history

val_loss, val_acc = model.evaluate(X_val, y_val)
print("Validation Loss:", val_loss)
print("Validation Accuracy:", val_acc)

print(f"Validation Accuracy: {val_acc * 100:.2f}%")

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""The blue line represents the training accuracy which consistently increases over the training steps while the orange line represents the validation accuracy which fluctuates slightly but shows a positive trend. By the end of the training the model achieves a training accuracy of around 96.81% and a validation accuracy of 97.13% indicating the model performs well on both training and validation data suggesting good generalization capability."""

test_data = pd.read_csv('/content/test.csv')
X_test = test_data.values / 255.0
X_test = X_test.reshape(-1, 28, 28, 1)
predictions = model.predict(X_test)
predicted_labels = np.argmax(predictions, axis=1)
for i in range(5):
  plt.imshow(X_test[i].reshape(28, 28), cmap='gray')
  plt.title(f"Predicted Label: {predicted_labels[i]}")
  plt.axis('off')
  plt.show()